# Generated by Django 5.0.1 on 2024-10-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0002_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(choices=[('jefa', 'Jefa'), ('empleado', 'Empleado')], default='empleado', max_length=10),
        ),
    ]
