# Generated by Django 5.0.1 on 2024-11-12 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0005_productos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pantalones',
        ),
        migrations.DeleteModel(
            name='Poleras',
        ),
        migrations.DeleteModel(
            name='Zapatos',
        ),
    ]
