# Generated by Django 5.0.1 on 2024-12-28 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0008_movimientos_delete_movimiento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movimientos',
            new_name='Movimiento',
        ),
    ]
