# Generated by Django 5.0.1 on 2024-12-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0009_rename_movimientos_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.CharField(choices=[('Pantalones', 'Pantalones'), ('Poleras', 'Poleras'), ('Zapatos', 'Zapatos')], default='Poleras', max_length=100),
        ),
        migrations.AddField(
            model_name='productos',
            name='talla',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='S', max_length=50),
        ),
    ]
