# Generated by Django 5.0.1 on 2024-12-29 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0010_productos_categoria_productos_talla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='color',
        ),
    ]
